repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.4'
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.24.0'
    hooks:
      - id: yapf
