# configure updates globally
update: all

# configure dependency pinning globally
pin: True

# update schedule
schedule: "every day"

# search for requirement files
search: False

# Specify requirement files by hand
requirements:
  - Pipfile:
      # update all dependencies and pin them
      update: all
      pin: True
  - setup.py:
      update: all
      pin: True

# add a label to pull requests
label_prs: dependencies

# assign users to pull requests
assignees:
 - GustavoKatel

# configure the branch prefix the bot is using
branch_prefix: pyup/

# set a global prefix for PRs
pr_prefix: "Bump Version: "
