language: python
branches:
  only:
  - master
  - "/^v\\d+.\\d+(.\\d+)?(-\\S*)?$/"
  - "/^feat\\/.*$/"
matrix:
  include:
  - os: linux
    python: '3.5'
  - os: linux
    python: '3.6'
  - os: linux
    python: 3.7-dev
  - os: osx
    language: generic
    env: PYTHON=3.5.6
  - os: osx
    language: generic
    env: PYTHON=3.6.6
  - os: osx
    language: generic
    env: PYTHON=3.7.0
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
    choco install miniconda3 --params="'/AddToPath:1'"
    conda config --add channels conda-forge
    conda create -n py$PYTHON python=$PYTHON
    activate py$PYTHON
  fi
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=pushbullet_cli
after_success:
- codecov
deploy:
  provider: pypi
  user: GustavoKatel
  password:
    secure: RK/+QxpDoooEa37Ux2IYq8bbSnWtrHG+I1bkAgNiqh8XAxZVpH1ssx7upEy0kNLVw0U6H6nPTKlol8DQs4iQ7qXjYToKa+RZdT6hCb5tmGCWDn0f6rTaYwjcuZIiAv3tDJxgnKShAD1+F44KA5+vIT+u/swLjv0WHUnwyx+fgxo=
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      secure: C35gKaP63zrNdFCw9ln6Y095u92q9hnAsqEsR2JpD1/U+WM1fBlrX1oOilXGH3e8/aTB2tKiYN3AaDPcG2raneBtaoU2caDIwo1MUGbO4HlZBiH73WfWLyTUoaEyqr/Q1+A0WnlTS04w4hXxSrvtkq89BDDN0AMD8d1hu7Qv2y0=
    on_success: always
    on_failure: always
    on_error: always
