language: python

branches:
  only:
    - master
    - /^v\d+.\d+(.\d+)?(-\S*)?$/
    - /^feat\/.*$/

sudo: false

matrix:
  include:
    - os: linux
      python: "3.5"

    - os: linux
      python: "3.6"

    - os: linux
      python: "3.7-dev"

    - os: osx
      language: generic
      env: PYTHON=3.5.6

    - os: osx
      language: generic
      env: PYTHON=3.6.6

    - os: osx
      language: generic
      env: PYTHON=3.7.0

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
    choco install miniconda3 --params="'/AddToPath:1'"
    conda config --add channels conda-forge
    conda create -n py$PYTHON python=$PYTHON
    activate py$PYTHON
  fi

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest --cov=pushbullet_cli

after_success:
  - codecov

deploy:
  provider: pypi
  user: GustavoKatel
  password:
    secure: V8r7yhJ+utgWStp0/LHlPI6qvNekgI1c/SlIooD4LKoFBmLIMJR0EvblAazT0h6Wj3tE0B0ZyzySUHwDxgt+zXbWyQb4pcZ2PxFpPYTBqk0TxxuVLMRpMIs4y5RSGpFXyN6qEaJ9MCYhlGc9on9R5D5trlIlJxLsOVUh8YPL8v2sc+krLl2DAe48VupkttVnie5jjXDG11U8WH/lOixVgQO9qxSxowHoOc50tkzGyi8GrPS0c91jl+T/BA5J1qOsbQSWrvAXKzbay/GLidjjiAoNImSpHRhMRcBc4mSnXZaeNa9EtJS1RHp2WwA8Bs7ubXPgLK243dw8dHoOOngDvjg1qd1VqP+q+PcT3VOGR8zyIi9s5ObIygu57BPAEHQLYAdf4PjwaAPJF5YH4CwX27cZuG9xJc8gzbIc0j2A4K6K9jFIRNgj53rmRdMS3qEB1v6VWb/P2DComcK3uUlXtwHVgYPmdLRDp1JuVRn+9HXW/uEzi7dMQuDQtLNpl0ku6RECzugb0qpba8s/KTiVgIYzyMbcS4LlBfSmHG8udQo0lSXe2lvYxniFOUi016lWhJ/K8spJMZ/1dE6Nu/MoWv7tob6YdWXwzLAaWIIuKxZOrwq9ZCR3zJzECV4+lNuQSleOZCwJkBCycha+PD7qw3+S0vEVuqe8cmXEDYtBXdA=
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      secure: C35gKaP63zrNdFCw9ln6Y095u92q9hnAsqEsR2JpD1/U+WM1fBlrX1oOilXGH3e8/aTB2tKiYN3AaDPcG2raneBtaoU2caDIwo1MUGbO4HlZBiH73WfWLyTUoaEyqr/Q1+A0WnlTS04w4hXxSrvtkq89BDDN0AMD8d1hu7Qv2y0=
    on_success: always
    on_failure: always
    on_error: always
